apiVersion: v1
kind: Pod
metadata:
  name: local-video-gui
spec:
  nodeName: kworker1.dragon.com # schedule pod to specific node
  containers:
  - name: my-first-pod
    image: andreamora/imagerepo:vlcnoentrypoint
    env:
    - name: DISPLAY
      value: :0
    stdin: true
    tty: true
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /tmp/.X11-unix
      name: video
    - mountPath: /home/Video
      name: storagevideo
    command: ["/bin/sh","-c"]
    args: ["vlc /home/Video/videoNoSound.mp4"]
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1024Mi"
        cpu: "1"
  restartPolicy: OnFailure
  volumes:
  - name: video
    hostPath:
      path: /tmp/.X11-unix    # directory location on host
  - name: storagevideo
    hostPath:
      path: /home/vagrant/Desktop/Video
